SELECT
	AGREEPERS.AGREENBR "Agreement Number", /*This is not the card agreement*/
	INITCAP(PERS.FIRSTNAME) || ' ' || INITCAP(PERS.LASTNAME) "Name",
	AGREEPERS.ACTIVEYN "Active eAgreement (YN)",
	AGREEPERS.DATELASTMAINT "Last Access Date",
	CARDAGREEMENT.PREFIX || CARDAGREEMENT.CARDNBR "PAN" /*Multiple PANs are returned, a way to selet only the PAN used for online banking needs to be idendified*/
FROM AGREEPERS
INNER JOIN PERS
	ON AGREEPERS.PERSNBR = PERS.PERSNBR
LEFT OUTER JOIN CARDAGREEMENT
	ON AGREEPERS.PERSNBR = CARDAGREEMENT.OWNERPERSNBR
WHERE
	CARDAGREEMENT.VALIDYN = 'Y'
ORDER BY
	PERS.LASTNAME ASC,
	PERS.FIRSTNAME ASC
