Select DISTINCT
  (DECODE(WH_ACCTCOMMON.CURRMIACCTTYPCD,
    'CI03','Business Accounts',
    'CI17','Business Accounts',
    'CI18','Business Accounts',
    'CN16','Business Accounts',
    'CN19','Business Accounts',
    'Personal Account')) AS "Product Type Code",
  WH_ACCTCOMMON.PRODUCT AS "Product",
  WH_ACCTCOMMON.ACCTNBR AS "Account Number",
  WH_ACCTCOMMON.OWNERSORTNAME AS "Lastname, Firstname",
  WH_ACCTCOMMON.NOTEBAL AS "Balance",
  ACCTMEMOBALTYP.BALAMT,
  MAX(ACCTREVIEWHIST.REVIEWDATE),
  WH_ACCTDEPOSIT.LIMITODBAL AS "LIMITODBAL",
  WH_ACCTDEPOSIT.ODEXCESSBAL AS "ODEXCESSBAL"
FROM
  WH_ACCTCOMMON,
  ACCTMEMOBALTYP,
  ACCTREVIEWHIST,
  WH_ACCTDEPOSIT
WHERE
  ((UPPER(ACCTMEMOBALTYP.MEMOBALTYPCD) = 'MOVD')
  AND (UPPER(WH_ACCTCOMMON.MJACCTTYPCD) = 'CK')
  AND (ACCTMEMOBALTYP.BALAMT > 0)
  AND (WH_ACCTCOMMON.NOTEBAL < 0)
  AND (WH_ACCTCOMMON.EFFDATE = TO_DATE('05/15/2019','MM/DD/YYYY'))
  AND ((UPPER(WH_ACCTCOMMON.CURRACCTSTATCD) <> 'CLS') 
  AND (UPPER(WH_ACCTCOMMON.CURRACCTSTATCD) <> ' CO')))
  AND ((WH_ACCTCOMMON.ACCTNBR = WH_ACCTDEPOSIT.ACCTNBR)
  AND (WH_ACCTCOMMON.EFFDATE = WH_ACCTDEPOSIT.EFFDATE))
  AND ((WH_ACCTCOMMON.ACCTNBR = ACCTMEMOBALTYP.ACCTNBR))
  AND ((WH_ACCTCOMMON.ACCTNBR = ACCTREVIEWHIST.ACCTNBR(+)))
GROUP BY
  (DECODE(WH_ACCTCOMMON.CURRMIACCTTYPCD,
    'CI03','Business Accounts',
    'CI17','Business Accounts',
    'CI18','Business Accounts',
    'CN16','Business Accounts',
    'CN19','Business Accounts',
    'Personal Account')),
    WH_ACCTCOMMON.PRODUCT,
    WH_ACCTCOMMON.ACCTNBR,
    WH_ACCTCOMMON.OWNERSORTNAME,
    WH_ACCTCOMMON.NOTEBAL,
    ACCTMEMOBALTYP.BALAMT,
    WH_ACCTDEPOSIT.LIMITODBAL,
    WH_ACCTDEPOSIT.ODEXCESSBAL
